<Project Sdk="Microsoft.NET.Sdk">
  <Sdk Name="Microsoft.DotNet.PackageValidation" Version="1.0.0-preview.7.21379.12" />
  <PropertyGroup>
    <Description>Microsoft Graph Client Library allows you to call Office 365, Azure AD and other Microsoft services through a single unified developer experience.</Description>
    <Copyright>© Microsoft Corporation. All rights reserved.</Copyright>
    <AssemblyTitle>Microsoft Graph V1.0 Service Client Library</AssemblyTitle>
    <Authors>Microsoft</Authors>
    <TargetFrameworks>netstandard2.0;netstandard2.1;net8.0;net10.0</TargetFrameworks>
    <LangVersion>latest</LangVersion>
    <PreserveCompilationContext>false</PreserveCompilationContext>
    <AssemblyName>Microsoft.Graph</AssemblyName>
    <PackageId>Microsoft.Graph</PackageId>
    <PackageTags>Microsoft Office365;Graph;GraphServiceClient;Outlook;OneDrive;AzureAD;GraphAPI;Productivity;SharePoint;Intune;SDK</PackageTags>
    <PackageProjectUrl>https://developer.microsoft.com/graph</PackageProjectUrl>
    <PackageRequireLicenseAcceptance>true</PackageRequireLicenseAcceptance>
    <PackageLicenseFile>LICENSE.txt</PackageLicenseFile>
    <PackageIconUrl>http://go.microsoft.com/fwlink/?LinkID=288890</PackageIconUrl>
    <RepositoryUrl>https://github.com/microsoftgraph/msgraph-sdk-dotnet</RepositoryUrl>
    <NetStandardImplicitPackageVersion Condition=" '$(TargetFramework)' == 'netstandard2.0' ">2.0.0</NetStandardImplicitPackageVersion>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <SignAssembly>false</SignAssembly>
    <DelaySign>false</DelaySign>
    <AssemblyOriginatorKeyFile>35MSSharedLib1024.snk</AssemblyOriginatorKeyFile>
    <AutoGenerateBindingRedirects>true</AutoGenerateBindingRedirects>
    <!-- x-release-please-start-version -->
    <VersionPrefix>6.7.0</VersionPrefix>
    <!-- x-release-please-end -->
    <!-- VersionPrefix minor version should not be set when the change comes from the generator. It will be updated automatically. -->
    <!-- VersionPrefix minor version must be manually set when making manual changes to code. -->
    <!-- VersionPrefix major and patch versions must be manually set. -->
    <PackageReleaseNotes>
https://github.com/microsoftgraph/msgraph-sdk-dotnet/blob/main/CHANGELOG.md
    </PackageReleaseNotes>
    <PublishRepositoryUrl>true</PublishRepositoryUrl>
    <EmbedUntrackedSources>true</EmbedUntrackedSources>
    <Deterministic>true</Deterministic>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <NoWarn>$(NoWarn);NU5048;NETSDK1138;1701;1702;1705;1591</NoWarn>
  </PropertyGroup>
  <PropertyGroup Condition="$([MSBuild]::IsTargetFrameworkCompatible('$(TargetFramework)','net5.0'))">
    <IsTrimmable>true</IsTrimmable>
  </PropertyGroup>
  <!-- https://github.com/clairernovotny/DeterministicBuilds#deterministic-builds -->
  <PropertyGroup Condition="'$(TF_BUILD)' == 'true'">
    <ContinuousIntegrationBuild>true</ContinuousIntegrationBuild>
  </PropertyGroup>
  <ItemGroup>
    <Compile Remove="Extensions\**" />
    <Compile Remove="Generated\Admin\**" />
    <Compile Remove="Generated\AgreementAcceptances\**" />
    <Compile Remove="Generated\Agreements\**" />
    <Compile Remove="Generated\AppCatalogs\**" />
    <Compile Remove="Generated\ApplicationsWithAppId\**" />
    <Compile Remove="Generated\ApplicationsWithUniqueName\**" />
    <Compile Remove="Generated\Applications\**" />
    <Compile Remove="Generated\ApplicationTemplates\**" />
    <Compile Remove="Generated\AuditLogs\**" />
    <Compile Remove="Generated\AuthenticationMethodConfigurations\**" />
    <Compile Remove="Generated\AuthenticationMethodsPolicy\**" />
    <Compile Remove="Generated\CertificateBasedAuthConfiguration\**" />
    <Compile Remove="Generated\Chats\**" />
    <Compile Remove="Generated\Communications\**" />
    <Compile Remove="Generated\Compliance\**" />
    <Compile Remove="Generated\Connections\**" />
    <Compile Remove="Generated\Contacts\**" />
    <Compile Remove="Generated\Contracts\**" />
    <Compile Remove="Generated\DataPolicyOperations\**" />
    <Compile Remove="Generated\DeviceAppManagement\**" />
    <Compile Remove="Generated\DeviceManagement\**" />
    <Compile Remove="Generated\DevicesWithDeviceId\**" />
    <Compile Remove="Generated\Devices\**" />
    <Compile Remove="Generated\DirectoryNamespace\**" />
    <Compile Remove="Generated\DirectoryObjects\**" />
    <Compile Remove="Generated\DirectoryRolesWithRoleTemplateId\**" />
    <Compile Remove="Generated\DirectoryRoles\**" />
    <Compile Remove="Generated\DirectoryRoleTemplates\**" />
    <Compile Remove="Generated\DomainDnsRecords\**" />
    <Compile Remove="Generated\Domains\**" />
    <Compile Remove="Generated\Drives\**" />
    <Compile Remove="Generated\Education\**" />
    <Compile Remove="Generated\EmployeeExperience\**" />
    <Compile Remove="Generated\External\**" />
    <Compile Remove="Generated\FilterOperators\**" />
    <Compile Remove="Generated\Functions\**" />
    <Compile Remove="Generated\GroupLifecyclePolicies\**" />
    <Compile Remove="Generated\GroupSettings\**" />
    <Compile Remove="Generated\GroupSettingTemplates\**" />
    <Compile Remove="Generated\GroupsWithUniqueName\**" />
    <Compile Remove="Generated\Groups\**" />
    <Compile Remove="Generated\IdentityGovernance\**" />
    <Compile Remove="Generated\IdentityProtection\**" />
    <Compile Remove="Generated\IdentityProviders\**" />
    <Compile Remove="Generated\Identity\**" />
    <Compile Remove="Generated\InformationProtection\**" />
    <Compile Remove="Generated\Invitations\**" />
    <Compile Remove="Generated\Me\**" />
    <Compile Remove="Generated\Models\**" />
    <Compile Remove="Generated\Oauth2PermissionGrants\**" />
    <Compile Remove="Generated\Organization\**" />
    <Compile Remove="Generated\PermissionGrants\**" />
    <Compile Remove="Generated\Places\**" />
    <Compile Remove="Generated\Planner\**" />
    <Compile Remove="Generated\Policies\**" />
    <Compile Remove="Generated\Print\**" />
    <Compile Remove="Generated\Privacy\**" />
    <Compile Remove="Generated\Reports\**" />
    <Compile Remove="Generated\RoleManagement\**" />
    <Compile Remove="Generated\SchemaExtensions\**" />
    <Compile Remove="Generated\ScopedRoleMemberships\**" />
    <Compile Remove="Generated\Search\**" />
    <Compile Remove="Generated\Security\**" />
    <Compile Remove="Generated\ServicePrincipalsWithAppId\**" />
    <Compile Remove="Generated\ServicePrincipals\**" />
    <Compile Remove="Generated\Shares\**" />
    <Compile Remove="Generated\Sites\**" />
    <Compile Remove="Generated\Solutions\**" />
    <Compile Remove="Generated\Storage\**" />
    <Compile Remove="Generated\SubscribedSkus\**" />
    <Compile Remove="Generated\Subscriptions\**" />
    <Compile Remove="Generated\TeamsTemplates\**" />
    <Compile Remove="Generated\Teams\**" />
    <Compile Remove="Generated\Teamwork\**" />
    <Compile Remove="Generated\TenantRelationships\**" />
    <Compile Remove="Generated\UsersWithUserPrincipalName\**" />
    <Compile Remove="Generated\Users\**" />
    <EmbeddedResource Remove="Extensions\**" />
    <EmbeddedResource Remove="Generated\Admin\**" />
    <EmbeddedResource Remove="Generated\AgreementAcceptances\**" />
    <EmbeddedResource Remove="Generated\Agreements\**" />
    <EmbeddedResource Remove="Generated\AppCatalogs\**" />
    <EmbeddedResource Remove="Generated\ApplicationsWithAppId\**" />
    <EmbeddedResource Remove="Generated\ApplicationsWithUniqueName\**" />
    <EmbeddedResource Remove="Generated\Applications\**" />
    <EmbeddedResource Remove="Generated\ApplicationTemplates\**" />
    <EmbeddedResource Remove="Generated\AuditLogs\**" />
    <EmbeddedResource Remove="Generated\AuthenticationMethodConfigurations\**" />
    <EmbeddedResource Remove="Generated\AuthenticationMethodsPolicy\**" />
    <EmbeddedResource Remove="Generated\CertificateBasedAuthConfiguration\**" />
    <EmbeddedResource Remove="Generated\Chats\**" />
    <EmbeddedResource Remove="Generated\Communications\**" />
    <EmbeddedResource Remove="Generated\Compliance\**" />
    <EmbeddedResource Remove="Generated\Connections\**" />
    <EmbeddedResource Remove="Generated\Contacts\**" />
    <EmbeddedResource Remove="Generated\Contracts\**" />
    <EmbeddedResource Remove="Generated\DataPolicyOperations\**" />
    <EmbeddedResource Remove="Generated\DeviceAppManagement\**" />
    <EmbeddedResource Remove="Generated\DeviceManagement\**" />
    <EmbeddedResource Remove="Generated\DevicesWithDeviceId\**" />
    <EmbeddedResource Remove="Generated\Devices\**" />
    <EmbeddedResource Remove="Generated\DirectoryNamespace\**" />
    <EmbeddedResource Remove="Generated\DirectoryObjects\**" />
    <EmbeddedResource Remove="Generated\DirectoryRolesWithRoleTemplateId\**" />
    <EmbeddedResource Remove="Generated\DirectoryRoles\**" />
    <EmbeddedResource Remove="Generated\DirectoryRoleTemplates\**" />
    <EmbeddedResource Remove="Generated\DomainDnsRecords\**" />
    <EmbeddedResource Remove="Generated\Domains\**" />
    <EmbeddedResource Remove="Generated\Drives\**" />
    <EmbeddedResource Remove="Generated\Education\**" />
    <EmbeddedResource Remove="Generated\EmployeeExperience\**" />
    <EmbeddedResource Remove="Generated\External\**" />
    <EmbeddedResource Remove="Generated\FilterOperators\**" />
    <EmbeddedResource Remove="Generated\Functions\**" />
    <EmbeddedResource Remove="Generated\GroupLifecyclePolicies\**" />
    <EmbeddedResource Remove="Generated\GroupSettings\**" />
    <EmbeddedResource Remove="Generated\GroupSettingTemplates\**" />
    <EmbeddedResource Remove="Generated\GroupsWithUniqueName\**" />
    <EmbeddedResource Remove="Generated\Groups\**" />
    <EmbeddedResource Remove="Generated\IdentityGovernance\**" />
    <EmbeddedResource Remove="Generated\IdentityProtection\**" />
    <EmbeddedResource Remove="Generated\IdentityProviders\**" />
    <EmbeddedResource Remove="Generated\Identity\**" />
    <EmbeddedResource Remove="Generated\InformationProtection\**" />
    <EmbeddedResource Remove="Generated\Invitations\**" />
    <EmbeddedResource Remove="Generated\Me\**" />
    <EmbeddedResource Remove="Generated\Models\**" />
    <EmbeddedResource Remove="Generated\Oauth2PermissionGrants\**" />
    <EmbeddedResource Remove="Generated\Organization\**" />
    <EmbeddedResource Remove="Generated\PermissionGrants\**" />
    <EmbeddedResource Remove="Generated\Places\**" />
    <EmbeddedResource Remove="Generated\Planner\**" />
    <EmbeddedResource Remove="Generated\Policies\**" />
    <EmbeddedResource Remove="Generated\Print\**" />
    <EmbeddedResource Remove="Generated\Privacy\**" />
    <EmbeddedResource Remove="Generated\Reports\**" />
    <EmbeddedResource Remove="Generated\RoleManagement\**" />
    <EmbeddedResource Remove="Generated\SchemaExtensions\**" />
    <EmbeddedResource Remove="Generated\ScopedRoleMemberships\**" />
    <EmbeddedResource Remove="Generated\Search\**" />
    <EmbeddedResource Remove="Generated\Security\**" />
    <EmbeddedResource Remove="Generated\ServicePrincipalsWithAppId\**" />
    <EmbeddedResource Remove="Generated\ServicePrincipals\**" />
    <EmbeddedResource Remove="Generated\Shares\**" />
    <EmbeddedResource Remove="Generated\Sites\**" />
    <EmbeddedResource Remove="Generated\Solutions\**" />
    <EmbeddedResource Remove="Generated\Storage\**" />
    <EmbeddedResource Remove="Generated\SubscribedSkus\**" />
    <EmbeddedResource Remove="Generated\Subscriptions\**" />
    <EmbeddedResource Remove="Generated\TeamsTemplates\**" />
    <EmbeddedResource Remove="Generated\Teams\**" />
    <EmbeddedResource Remove="Generated\Teamwork\**" />
    <EmbeddedResource Remove="Generated\TenantRelationships\**" />
    <EmbeddedResource Remove="Generated\UsersWithUserPrincipalName\**" />
    <EmbeddedResource Remove="Generated\Users\**" />
    <None Remove="Extensions\**" />
    <None Remove="Generated\Admin\**" />
    <None Remove="Generated\AgreementAcceptances\**" />
    <None Remove="Generated\Agreements\**" />
    <None Remove="Generated\AppCatalogs\**" />
    <None Remove="Generated\ApplicationsWithAppId\**" />
    <None Remove="Generated\ApplicationsWithUniqueName\**" />
    <None Remove="Generated\Applications\**" />
    <None Remove="Generated\ApplicationTemplates\**" />
    <None Remove="Generated\AuditLogs\**" />
    <None Remove="Generated\AuthenticationMethodConfigurations\**" />
    <None Remove="Generated\AuthenticationMethodsPolicy\**" />
    <None Remove="Generated\CertificateBasedAuthConfiguration\**" />
    <None Remove="Generated\Chats\**" />
    <None Remove="Generated\Communications\**" />
    <None Remove="Generated\Compliance\**" />
    <None Remove="Generated\Connections\**" />
    <None Remove="Generated\Contacts\**" />
    <None Remove="Generated\Contracts\**" />
    <None Remove="Generated\DataPolicyOperations\**" />
    <None Remove="Generated\DeviceAppManagement\**" />
    <None Remove="Generated\DeviceManagement\**" />
    <None Remove="Generated\DevicesWithDeviceId\**" />
    <None Remove="Generated\Devices\**" />
    <None Remove="Generated\DirectoryNamespace\**" />
    <None Remove="Generated\DirectoryObjects\**" />
    <None Remove="Generated\DirectoryRolesWithRoleTemplateId\**" />
    <None Remove="Generated\DirectoryRoles\**" />
    <None Remove="Generated\DirectoryRoleTemplates\**" />
    <None Remove="Generated\DomainDnsRecords\**" />
    <None Remove="Generated\Domains\**" />
    <None Remove="Generated\Drives\**" />
    <None Remove="Generated\Education\**" />
    <None Remove="Generated\EmployeeExperience\**" />
    <None Remove="Generated\External\**" />
    <None Remove="Generated\FilterOperators\**" />
    <None Remove="Generated\Functions\**" />
    <None Remove="Generated\GroupLifecyclePolicies\**" />
    <None Remove="Generated\GroupSettings\**" />
    <None Remove="Generated\GroupSettingTemplates\**" />
    <None Remove="Generated\GroupsWithUniqueName\**" />
    <None Remove="Generated\Groups\**" />
    <None Remove="Generated\IdentityGovernance\**" />
    <None Remove="Generated\IdentityProtection\**" />
    <None Remove="Generated\IdentityProviders\**" />
    <None Remove="Generated\Identity\**" />
    <None Remove="Generated\InformationProtection\**" />
    <None Remove="Generated\Invitations\**" />
    <None Remove="Generated\Me\**" />
    <None Remove="Generated\Models\**" />
    <None Remove="Generated\Oauth2PermissionGrants\**" />
    <None Remove="Generated\Organization\**" />
    <None Remove="Generated\PermissionGrants\**" />
    <None Remove="Generated\Places\**" />
    <None Remove="Generated\Planner\**" />
    <None Remove="Generated\Policies\**" />
    <None Remove="Generated\Print\**" />
    <None Remove="Generated\Privacy\**" />
    <None Remove="Generated\Reports\**" />
    <None Remove="Generated\RoleManagement\**" />
    <None Remove="Generated\SchemaExtensions\**" />
    <None Remove="Generated\ScopedRoleMemberships\**" />
    <None Remove="Generated\Search\**" />
    <None Remove="Generated\Security\**" />
    <None Remove="Generated\ServicePrincipalsWithAppId\**" />
    <None Remove="Generated\ServicePrincipals\**" />
    <None Remove="Generated\Shares\**" />
    <None Remove="Generated\Sites\**" />
    <None Remove="Generated\Solutions\**" />
    <None Remove="Generated\Storage\**" />
    <None Remove="Generated\SubscribedSkus\**" />
    <None Remove="Generated\Subscriptions\**" />
    <None Remove="Generated\TeamsTemplates\**" />
    <None Remove="Generated\Teams\**" />
    <None Remove="Generated\Teamwork\**" />
    <None Remove="Generated\TenantRelationships\**" />
    <None Remove="Generated\UsersWithUserPrincipalName\**" />
    <None Remove="Generated\Users\**" />
  </ItemGroup>
  <ItemGroup>
    <None Remove="Properties\Graph.rd.xml" />
  </ItemGroup>
  <ItemGroup>
    <Compile Include="Extensions\CustomBatchRequestBuilder.cs" />
    <Compile Include="Extensions\DateTimeTimeZoneExtensions.cs" />
    <Compile Include="Generated\Me\MeRequestBuilder.cs" />
    <Compile Include="Generated\Me\SendMail\SendMailPostRequestBody.cs" />
    <Compile Include="Generated\Me\SendMail\SendMailRequestBuilder.cs" />
    <Compile Include="Generated\Models\Attachment.cs" />
    <Compile Include="Generated\Models\BaseCollectionPaginationCountResponse.cs" />
    <Compile Include="Generated\Models\BodyType.cs" />
    <!--<Compile Include="Generated\Models\CalendarSharingAction.cs" />
    <Compile Include="Generated\Models\CalendarSharingActionImportance.cs" />
    <Compile Include="Generated\Models\CalendarSharingActionType.cs" />
    <Compile Include="Generated\Models\CalendarSharingMessage.cs" />
    <Compile Include="Generated\Models\CalendarSharingMessageAction.cs" />-->
    <Compile Include="Generated\Models\DateTimeTimeZone.cs" />
    <Compile Include="Generated\Models\DirectoryObject.cs" />
    <Compile Include="Generated\Models\EmailAddress.cs" />
    <Compile Include="Generated\Models\Entity.cs" />
    <!--<Compile Include="Generated\Models\Event.cs" />
    <Compile Include="Generated\Models\EventMessage.cs" />
    <Compile Include="Generated\Models\EventMessageRequest.cs" />
    <Compile Include="Generated\Models\EventMessageResponse.cs" />
    <Compile Include="Generated\Models\EventType.cs" />-->
    <Compile Include="Generated\Models\Extension.cs" />
    <Compile Include="Generated\Models\FileAttachment.cs" />
    <Compile Include="Generated\Models\FollowupFlag.cs" />
    <Compile Include="Generated\Models\FollowupFlagStatus.cs" />
    <!--<Compile Include="Generated\Models\Identity.cs" />
    <Compile Include="Generated\Models\IdentitySet.cs" />-->
    <Compile Include="Generated\Models\Importance.cs" />
    <Compile Include="Generated\Models\InferenceClassificationType.cs" />
    <Compile Include="Generated\Models\InternetMessageHeader.cs" />
    <Compile Include="Generated\Models\ItemAttachment.cs" />
    <Compile Include="Generated\Models\ItemBody.cs" />
    <!--<Compile Include="Generated\Models\Location.cs" />-->
    <Compile Include="Generated\Models\MeetingMessageType.cs" />
    <Compile Include="Generated\Models\Message.cs" />
    <Compile Include="Generated\Models\MultiValueLegacyExtendedProperty.cs" />
    <Compile Include="Generated\Models\ODataErrors\ErrorDetails.cs" />
    <Compile Include="Generated\Models\ODataErrors\InnerError.cs" />
    <Compile Include="Generated\Models\ODataErrors\MainError.cs" />
    <Compile Include="Generated\Models\ODataErrors\ODataError.cs" />
    <Compile Include="Generated\Models\OpenTypeExtension.cs" />
    <Compile Include="Generated\Models\OutlookGeoCoordinates.cs" />
    <Compile Include="Generated\Models\OutlookItem.cs" />
    <Compile Include="Generated\Models\Recipient.cs" />
    <Compile Include="Generated\Models\ReferenceAttachment.cs" />
    <!--<Compile Include="Generated\Models\Request.cs" />-->
    <Compile Include="Generated\Models\ResponseType.cs" />
    <Compile Include="Generated\Models\SingleValueLegacyExtendedProperty.cs" />
    <Compile Include="Generated\Models\User.cs" />
    <Compile Include="Generated\Users\Item\SendMail\SendMailPostRequestBody.cs" />
    <Compile Include="Generated\Users\Item\SendMail\SendMailRequestBuilder.cs" />
    <Compile Include="Generated\Users\Item\UserItemRequestBuilder.cs" />
    <Compile Include="Generated\Users\UsersRequestBuilder.cs" />
    <Compile Include="Generated\Users\ValidateProperties\ValidatePropertiesPostRequestBody.cs" />
    <Compile Include="Generated\Users\ValidateProperties\ValidatePropertiesRequestBuilder.cs" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Properties\Graph.rd.xml" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Graph.Core" Version="4.*" />
    <PackageReference Include="Microsoft.SourceLink.GitHub" Version="10.0.303" PrivateAssets="All" />
  </ItemGroup>
  <ItemGroup>
    <None Include="..\..\LICENSE.txt">
      <Pack>True</Pack>
      <PackagePath>
      </PackagePath>
    </None>
    <None Include="..\..\README.md">
      <Pack>True</Pack>
      <PackagePath>
      </PackagePath>
    </None>
  </ItemGroup>
</Project>
